# Generated by Django 2.2.7 on 2019-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
